# Benchmark Definitions Configuration
# Defines benchmarks for performance comparison

# Primary Benchmarks
primary_benchmarks:
  sp_midcap_400:
    name: "S&P MidCap 400"
    symbol: "MDY"
    description: "S&P MidCap 400 Index - Primary benchmark for mid-cap equity strategies"
    rebalancing: quarterly
    
  equal_weight_midcap:
    name: "Equal Weight MidCap"
    description: "Equal-weighted portfolio of S&P MidCap 400 constituents"
    construction_method: "equal_weight"
    rebalancing: monthly
    min_weight: 0.002  # ~1/400 for 400 stocks
    
  russell_midcap:
    name: "Russell MidCap Index"
    symbol: "IWR"
    description: "Russell MidCap Index - Alternative mid-cap benchmark"
    rebalancing: annual

# Constructed Benchmarks
constructed_benchmarks:
  mean_variance_optimal:
    name: "Mean-Variance Optimal"
    description: "Mean-variance optimized portfolio using historical data"
    construction_method: "mean_variance"
    lookback_window: 252  # 1 year lookback
    rebalance_frequency: 21  # Monthly rebalancing
    min_weight: 0.01
    max_weight: 0.20
    risk_free_rate: 0.02
    
  risk_parity:
    name: "Risk Parity"
    description: "Risk parity weighted portfolio"
    construction_method: "risk_parity"
    target_volatility: 0.12  # 12% target volatility
    lookback_window: 126  # 6 months for volatility estimation
    rebalance_frequency: 21
    
  momentum_factor:
    name: "Momentum Factor"
    description: "Momentum-based factor portfolio"
    construction_method: "factor_weighted"
    factor_type: "momentum"
    lookback_window: 252
    rebalance_frequency: 63  # Quarterly

# Style Benchmarks
style_benchmarks:
  value:
    name: "Value Style"
    description: "Value-oriented mid-cap portfolio"
    style_factors: ["book_to_market", "earnings_yield", "sales_to_price"]
    
  growth:
    name: "Growth Style"
    description: "Growth-oriented mid-cap portfolio"
    style_factors: ["earnings_growth", "sales_growth", "roi_growth"]
    
  quality:
    name: "Quality Style"
    description: "Quality-focused mid-cap portfolio"
    style_factors: ["roe", "debt_to_equity", "earnings_stability"]

# Sector Benchmarks
sector_benchmarks:
  technology:
    name: "Technology Sector"
    sector_filter: "technology"
    
  healthcare:
    name: "Healthcare Sector" 
    sector_filter: "healthcare"
    
  financials:
    name: "Financials Sector"
    sector_filter: "financials"

# Multi-Asset Benchmarks
multi_asset_benchmarks:
  60_40_portfolio:
    name: "60/40 Stock-Bond Portfolio"
    allocations:
      stocks: 0.60  # S&P MidCap 400
      bonds: 0.40   # Aggregate Bond Index
    rebalancing: quarterly
    
  all_weather:
    name: "All Weather Portfolio"
    description: "Risk-balanced multi-asset portfolio"
    allocations:
      stocks: 0.30
      bonds: 0.55
      commodities: 0.075
      tips: 0.075

# Benchmark Configuration Settings
settings:
  default_currency: "USD"
  include_dividends: true
  adjust_for_survivorship: true
  minimum_history: 252  # Minimum 1 year of data required
  
  # Data sources and providers
  data_sources:
    primary: "bloomberg"
    secondary: "refinitiv"
    fallback: "yahoo_finance"
    
  # Benchmark construction parameters
  construction:
    min_market_cap: 1_000_000_000  # $1B minimum market cap
    max_market_cap: 10_000_000_000  # $10B maximum market cap
    min_liquidity: 1_000_000  # $1M minimum daily dollar volume
    
  # Performance comparison settings
  comparison:
    attribution_method: "brinson_fachler"  # Attribution methodology
    statistical_tests: ["t_test", "bootstrap", "block_bootstrap"]
    significance_level: 0.05
    
# Risk Factor Definitions
risk_factors:
  market:
    name: "Market Factor"
    proxy: "sp_midcap_400"
    description: "Overall market exposure"
    
  size:
    name: "Size Factor"
    proxy: "smb_midcap"  # Small minus big for mid-cap universe
    description: "Size effect within mid-cap range"
    
  value:
    name: "Value Factor"  
    proxy: "hml_midcap"  # High minus low book-to-market
    description: "Value vs growth characteristics"
    
  momentum:
    name: "Momentum Factor"
    proxy: "umd_midcap"  # Up minus down momentum
    description: "Price momentum effect"
    
  quality:
    name: "Quality Factor"
    proxy: "qmj_midcap"  # Quality minus junk
    description: "Quality characteristics"
    
  volatility:
    name: "Low Volatility Factor"
    proxy: "bab_midcap"  # Betting against beta
    description: "Low volatility anomaly"