# Statistical Validation Configuration for Performance Analytics
# Story 5.4: Performance Analytics and Statistical Validation

# Statistical Testing Parameters
statistical_testing:
  significance_level: 0.05
  confidence_level: 0.95
  sharpe_improvement_threshold: 0.2
  error_tolerance: 0.001  # 0.1% error tolerance for statistical calculations
  
# Bootstrap Configuration
bootstrap:
  n_samples: 10000
  confidence_intervals:
    - 0.90
    - 0.95
    - 0.99
  methods:
    - "percentile"
    - "bias_corrected"
    - "bca"
  random_state: 42
  parallel_jobs: -1  # Use all available CPUs

# Hypothesis Testing
hypothesis_testing:
  alpha: 0.05
  power: 0.80
  effect_size_threshold: 0.2  # Minimum meaningful Sharpe ratio improvement
  methods:
    - "jobson_korkie"
    - "asymptotic"
    - "bootstrap"

# Multiple Comparison Corrections
multiple_comparisons:
  methods:
    - "bonferroni"
    - "holm_sidak"
    - "benjamini_hochberg"
  family_wise_error_rate: 0.05

# Performance Metrics Configuration
performance_metrics:
  annualization_factor: 252  # Trading days per year
  risk_free_rate: 0.0  # Assume zero risk-free rate
  
  # Metrics to calculate
  basic_metrics:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "calmar_ratio"
    - "omega_ratio"
    - "information_ratio"
    
  risk_metrics:
    - "var_95"
    - "cvar_95"
    - "max_drawdown"
    - "downside_deviation"
    
  advanced_metrics:
    - "probabilistic_sharpe"
    - "deflated_sharpe"
    - "burke_ratio"
    - "martin_ratio"

# Rolling Window Analysis
rolling_analysis:
  window_months: 12
  step_months: 3
  min_observations: 252  # Minimum daily observations per window
  
  consistency_metrics:
    - "sharpe_stability"
    - "return_consistency"
    - "drawdown_consistency"
    - "rank_correlation"

# Sensitivity Analysis
sensitivity_analysis:
  transaction_costs:
    scenarios_bps: [5, 10, 15, 20, 25]  # Basis points
    
  market_regimes:
    volatility_thresholds:
      low: 0.8   # 80% of median volatility
      high: 1.2  # 120% of median volatility
      
  parameter_sensitivity:
    lookback_periods: [126, 252, 504, 756]  # 6M, 1Y, 2Y, 3Y
    rebalancing_frequencies: ["M", "Q", "6M"]  # Monthly, Quarterly, Semi-annual

# Quality Assurance Thresholds
quality_assurance:
  data_quality:
    min_coverage_ratio: 0.95  # 95% data availability
    max_gap_days: 5
    
  statistical_accuracy:
    reference_validation_tolerance: 0.001  # 0.1% tolerance vs reference implementations
    bootstrap_coverage_tolerance: 0.05     # ±5% coverage tolerance
    
  computational_constraints:
    max_execution_hours: 8.0
    gpu_memory_limit_gb: 11.0
    max_bootstrap_samples: 10000

# Publication Standards
publication:
  apa_compliance: true
  decimal_places: 4
  p_value_threshold: 0.001
  significance_stars:
    p_001: "***"
    p_01: "**"
    p_05: "*"
    
  table_formatting:
    include_confidence_intervals: true
    include_effect_sizes: true
    include_sample_sizes: true
    
# Academic Compliance
academic_compliance:
  reproducibility:
    save_random_states: true
    version_control_hashes: true
    environment_documentation: true
    
  statistical_disclosure:
    report_all_tests: true
    multiple_comparison_corrections: true
    effect_size_reporting: true
    confidence_interval_reporting: true
    
  methodology_transparency:
    document_assumptions: true
    report_limitations: true
    provide_data_availability: true