# Risk Metrics Configuration
# Configuration for comprehensive risk analytics and measurement

# Basic Risk Parameters
basic_risk:
  risk_free_rate: 0.02  # 2% annual risk-free rate
  trading_days_per_year: 252
  confidence_levels: [0.90, 0.95, 0.99]
  
# Value at Risk (VaR) Configuration
var_config:
  methods: ["historical", "parametric", "monte_carlo"]
  default_method: "historical"
  confidence_levels: [0.90, 0.95, 0.99]
  holding_period: 1  # 1 day holding period
  lookback_window: 252  # 1 year of data
  
  # Monte Carlo specific parameters
  monte_carlo:
    num_simulations: 10000
    random_seed: 42
    
  # Parametric VaR parameters
  parametric:
    distribution: "normal"  # Options: normal, t-distribution, skewed-t
    
# Expected Shortfall (Conditional VaR) Configuration
cvar_config:
  confidence_levels: [0.90, 0.95, 0.99]
  estimation_method: "historical"
  
# Tracking Error Configuration
tracking_error:
  annualization_factor: 252
  min_observations: 63  # Minimum 3 months
  rolling_windows: [63, 126, 252]  # 3M, 6M, 1Y rolling windows
  
# Downside Risk Measures
downside_risk:
  minimum_acceptable_returns:
    - 0.00  # 0% MAR
    - 0.02  # 2% MAR (risk-free rate)
    - 0.08  # 8% MAR (typical equity return expectation)
  
  # Downside deviation parameters
  downside_deviation:
    method: "full_sample"  # Options: full_sample, rolling
    rolling_window: 252
    
  # Semi-variance configuration
  semi_variance:
    threshold: 0.0  # Return threshold for semi-variance
    
# Drawdown Analysis
drawdown_config:
  # Maximum drawdown parameters
  max_drawdown:
    method: "peak_to_trough"
    include_recovery_time: true
    
  # Underwater curve analysis
  underwater_analysis:
    recovery_threshold: 0.95  # 95% recovery threshold
    
  # Conditional drawdown at risk
  cdar:
    confidence_levels: [0.90, 0.95, 0.99]
    
# Volatility Measures
volatility_config:
  # Standard volatility
  standard_volatility:
    annualization_factor: 252
    bias_correction: true
    
  # Realized volatility
  realized_volatility:
    frequency: "daily"  # daily, weekly, monthly
    
  # GARCH modeling
  garch:
    model_type: "GARCH(1,1)"
    max_lag: 5
    
  # Rolling volatility
  rolling_volatility:
    windows: [21, 63, 126, 252]  # 1M, 3M, 6M, 1Y
    
# Higher Moment Risk Measures
higher_moments:
  # Skewness configuration
  skewness:
    method: "sample"  # sample, adjusted
    
  # Kurtosis configuration  
  kurtosis:
    method: "sample"
    excess: true  # Report excess kurtosis
    
  # Co-skewness and co-kurtosis
  co_moments:
    calculate: true
    benchmark_required: true

# Correlation and Beta Analysis
correlation_config:
  # Correlation parameters
  correlation:
    method: "pearson"  # pearson, spearman, kendall
    rolling_windows: [63, 126, 252]
    
  # Beta calculation
  beta:
    method: "ols"  # ols, robust
    rolling_windows: [126, 252, 504]  # 6M, 1Y, 2Y
    
  # Time-varying correlation
  time_varying:
    method: "dcc_garch"  # Dynamic conditional correlation
    
# Regime-Dependent Risk
regime_risk:
  # Regime identification
  regime_detection:
    method: "markov_switching"  # markov_switching, volatility_threshold
    n_regimes: 2  # Bull/Bear markets
    
  # Regime-specific risk measures
  by_regime:
    calculate_var: true
    calculate_volatility: true
    calculate_correlations: true
    
# Stress Testing
stress_testing:
  # Historical stress tests
  historical_scenarios:
    - name: "dot_com_crash"
      start_date: "2000-03-01"
      end_date: "2002-10-01"
      
    - name: "financial_crisis"
      start_date: "2007-10-01" 
      end_date: "2009-03-01"
      
    - name: "covid_crisis"
      start_date: "2020-02-01"
      end_date: "2020-05-01"
      
  # Monte Carlo stress testing
  monte_carlo_stress:
    num_scenarios: 1000
    shock_magnitudes: [2, 3, 4]  # Standard deviations
    
# Risk Factor Analysis
risk_factors:
  # Factor risk decomposition
  factor_decomposition:
    factors: ["market", "size", "value", "momentum", "quality", "volatility"]
    method: "principal_components"  # principal_components, regression
    
  # Active risk analysis
  active_risk:
    calculate_component_contributions: true
    risk_budgeting: true
    
# Multi-Horizon Risk Analysis
multi_horizon:
  horizons: [1, 5, 21, 63, 126, 252]  # 1D, 1W, 1M, 3M, 6M, 1Y
  scaling_method: "sqrt_time"  # sqrt_time, empirical
  
# Risk Reporting
reporting:
  # Risk dashboard metrics
  dashboard_metrics:
    - "volatility"
    - "var_95" 
    - "max_drawdown"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "calmar_ratio"
    
  # Risk attribution
  attribution:
    include_factor_contributions: true
    include_residual_risk: true
    
  # Alerts and monitoring
  alerts:
    var_breach_threshold: 0.05  # Alert if VaR breached more than 5% of days
    drawdown_alert: 0.10  # Alert if current drawdown > 10%
    volatility_alert: 2.0   # Alert if current vol > 2x historical average

# Advanced Risk Models
advanced_models:
  # Copula models for dependence
  copula:
    type: "gaussian"  # gaussian, t-copula, clayton, gumbel
    
  # Extreme value theory
  extreme_value:
    method: "peaks_over_threshold"
    threshold_percentile: 0.95
    
  # Jump diffusion models
  jump_diffusion:
    estimate_jumps: true
    jump_intensity: "mle"  # Maximum likelihood estimation