graph:
  lookback_days: 756           # ~ 3 years of trading days (3*252)
  vol_window_days: 30          # realised volatility window used for similarity
  similarity: "distance_corr"  # per paper; "pearson" is available for sanity checks
  filter:
    method: "tmfg"             # "tmfg" | "mst" | "knn"
    k_neighbors: 5             # used only if method == "knn"
  make_undirected: true
  save_dir: "processed/graphs"

# Optional: dynamic membership (survivorship-aware)
membership:
  csv: "data/raw/universe_membership.csv"  # columns: ticker,start,end (YYYY-MM-DD). Leave blank to ignore.
