# LSTM model configuration for portfolio optimization

model_type: lstm

# Base training parameters
learning_rate: 0.001
batch_size: 32
max_epochs: 100
early_stopping_patience: 10
validation_split: 0.2

# LSTM architecture
architecture:
  hidden_size: 64          # LSTM hidden layer size
  num_layers: 2           # Number of LSTM layers
  dropout: 0.2            # Dropout rate for regularization
  bidirectional: false    # Use bidirectional LSTM
  
# Input/Output configuration  
sequence:
  sequence_length: 60      # 60-day input sequences (3 months)
  prediction_horizon: 1    # Predict 1 day ahead
  overlap: 0.5            # 50% overlap between sequences
  
# Feature configuration
features:
  node_features:
    - returns
    - volume  
    - volatility
    - momentum
    - technical_indicators
  
  # Time series features
  technical_indicators:
    - rsi
    - macd
    - bollinger_bands
    - moving_average
    
  feature_scaling: minmax   # Feature scaling method
  target_scaling: standard # Target scaling method

# Portfolio optimization integration
portfolio:
  prediction_type: returns    # Predict asset returns
  rebalancing_frequency: 21   # Monthly rebalancing
  lookback_window: 252       # 1 year lookback
  
# Training configuration
training:
  optimizer: adam
  weight_decay: 1e-5
  gradient_clipping: 1.0
  scheduler: step           # Learning rate scheduler
  scheduler_step_size: 30
  scheduler_gamma: 0.5
  
# Regularization
regularization:
  l1_lambda: 0.0           # L1 regularization
  l2_lambda: 1e-5          # L2 regularization
  label_smoothing: 0.0     # Label smoothing factor
  
# Data augmentation
augmentation:
  noise_std: 0.01          # Gaussian noise standard deviation
  time_shift_max: 5       # Maximum time shift in days
  scaling_range: [0.9, 1.1]  # Random scaling range
  
# Loss function
loss:
  type: mse                # Mean squared error
  alpha: 1.0               # Loss weighting factor
  
# Evaluation metrics
metrics:
  - mse
  - mae
  - sharpe_ratio
  - information_ratio
  - max_drawdown