architecture:
  input_features: 10
  hidden_dim: 64
  num_layers: 3
  num_attention_heads: 8
  dropout: 0.3
  edge_feature_dim: 3
  use_gatv2: true
  residual: true

training:
  learning_rate: 0.001
  weight_decay: 1e-5
  batch_size: 16
  max_epochs: 100
  patience: 15
  use_mixed_precision: true
  gradient_accumulation_steps: 4

graph_construction:
  lookback_days: 252
  methods: ['mst', 'tmfg', 'knn']
  knn_k_values: [5, 10, 15]
  use_edge_attr: true
